name: Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # weekly
    - cron: '* * * * 1'

env:
  UBUNTU_DIST: focal
  UBUNTU_VERSION: 20.04

jobs:
  determine-matrix:
    name: Determine what to build
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      versions: ${{ steps.matrix.outputs.versions }}

    steps:
      - uses: actions/checkout@v2

      - id: matrix
        run: |
          DOCKER=$(./scripts/get_docker_image_version.py)
          QGIS=$(./scripts/get_ubuntu_qgis_package_version.py -d ${UBUNTU_DIST})

          DOCKER_STABLE=$(echo "${DOCKER}" | jq ".stable" | sed 's/"//g' | cut -d- -f2)
          DOCKER_LTR=$(echo "${DOCKER}" | jq ".ltr" | sed 's/"//g' | sed 's/"//g' | cut -d- -f2)
          QGIS_STABLE=${UBUNTU_DIST}-$(echo "${QGIS}" | jq ".stable" | sed 's/"//g' | cut -d- -f2)
          QGIS_LTR=${UBUNTU_DIST}-$(echo "${QGIS}" | jq ".ltr" | sed 's/"//g' | cut -d- -f2)

          MATRIX="{\"release_type\":["

          echo "Existing stable docker: ${DOCKER_STABLE}"
          echo "Available stable QGIS: ${QGIS_STABLE}"
          UPDATE_STABLE=$(python3 -c "from packaging import version; print(1 if '${DOCKER_STABLE}' == 'null' or version.parse('${DOCKER_STABLE}') < version.parse('${QGIS_STABLE}') else 0)")
          if [[ ${UPDATE_STABLE} == 1 ]]; then
            echo "--> stable will be updated"
            MATRIX=${MATRIX}"\"stable\", "
          else
            echo "--> stable is up to date"
          fi

          echo "Existing LTR docker: ${DOCKER_LTR}"
          echo "Available LTR QGIS: ${QGIS_LTR}"
          UPDATE_LTR=$(python3 -c "from packaging import version; print(1 if '${DOCKER_LTR}' == 'null' or version.parse('${DOCKER_LTR}') < version.parse('${QGIS_LTR}') else 0)")
          if [[ ${UPDATE_LTR} == 1 ]]; then
            echo "--> LTR will be updated"
            MATRIX=${MATRIX}"\"ltr\","
          else
            echo "--> LTR is up to date"
          fi

          MATRIX=${MATRIX}"]}"
          echo "matrix: ${MATRIX}"
          echo "::set-output name=matrix::${MATRIX}"
          VERSIONS="{\"stable\":\"${QGIS_STABLE}\", \"ltr\":\"${QGIS_LTR}\"}"
          echo "versions: ${VERSIONS}"
          echo "::set-output name=versions::${VERSIONS}"


  build-docker:
    name: Build
    runs-on: ubuntu-latest
    needs: determine-matrix

    env:
      DOCKER_USERNAME: ${{ secrets.docker_username }}
      DOCKER_PASSWORD: ${{ secrets.docker_password }}

    strategy:
      matrix: ${{ fromJSON( needs.determine-matrix.outputs.matrix ) }}

    steps:
      - uses: actions/checkout@v2

      - name: Define parameters
        env:
          RELEASE_TYPE: ${{ matrix.release_type }}
          VERSIONS: ${{ needs.determine-matrix.outputs.versions }}
        run: |
          QGIS_VERSION=$(echo "${VERSIONS}" | jq ".${RELEASE_TYPE}" | sed 's/"//g')

          MAJOR_QGIS_VERSION=$(echo "${QGIS_VERSION}" | cut -d. -f1,2)

          if [[ ${RELEASE_TYPE} == ltr ]]; then
            QGIS_UBUNTU_PPA='ubuntu-ltr'
          else
            QGIS_UBUNTU_PPA='ubuntu'
          fi

          echo "RELEASE_TYPE=${RELEASE_TYPE}" >> $GITHUB_ENV
          echo "QGIS_VERSION=${QGIS_VERSION}" >> $GITHUB_ENV
          echo "MAJOR_QGIS_VERSION=${MAJOR_QGIS_VERSION}" >> $GITHUB_ENV
          echo "UBUNTU_DIST=${UBUNTU_DIST}" >> $GITHUB_ENV
          echo "QGIS_UBUNTU_PPA=${QGIS_UBUNTU_PPA}" >> $GITHUB_ENV

          echo "RELEASE_TYPE: ${RELEASE_TYPE}"
          echo "QGIS_VERSION: ${QGIS_VERSION}"
          echo "MAJOR_QGIS_VERSION: ${MAJOR_QGIS_VERSION}"
          echo "UBUNTU_DIST: ${UBUNTU_DIST}"
          echo "QGIS_UBUNTU_PPA: ${QGIS_UBUNTU_PPA}"

      - name: Docker build
        run: |
          docker build \
            --build-arg REPO=${QGIS_UBUNTU_PPA} \
            --build-arg UBUNTU_DIST=${UBUNTU_DIST} \
            --build-arg UBUNTU_VERSION=${UBUNTU_VERSION} \
            -t opengisch/qgis:${RELEASE_TYPE} .

      - name: Docker tag
        run: |
          docker tag opengisch/qgis:${RELEASE_TYPE} opengisch/qgis:${RELEASE_TYPE}
          docker tag opengisch/qgis:${RELEASE_TYPE} opengisch/qgis:${UBUNTU_DIST}-${MAJOR_QGIS_VERSION}
          docker tag opengisch/qgis:${RELEASE_TYPE} opengisch/qgis:${UBUNTU_DIST}-${QGIS_VERSION}

      - name: Docker push
        run: |
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

          docker push opengisch/qgis:${RELEASE_TYPE}
          docker push opengisch/qgis:${UBUNTU_DIST}-${MAJOR_QGIS_VERSION}
          docker push opengisch/qgis:${UBUNTU_DIST}-${QGIS_VERSION}



